#tomcat port
server:
  port: 9999
#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/market/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sts4?serverTimezone=Asia/Seoul
    username: root
    password: 1234
#mybatis
mybatis:
  type-aliases-package: data.dto,data.mapper
  mapper-locations:
  - /mapper/**/*.xml
